# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_agentconversation_agentmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleBusinessProfileConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_type", models.CharField(blank=True, max_length=32)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gbp_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Business Profile connection",
                "verbose_name_plural": "Google Business Profile connections",
            },
        ),
        migrations.CreateModel(
            name="ReviewsOverviewSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("star_rating", models.DecimalField(blank=True, decimal_places=2, max_digits=3, default=0, null=True)),
                ("previous_star_rating", models.DecimalField(blank=True, decimal_places=2, max_digits=3, default=0, null=True)),
                ("total_reviews", models.IntegerField(default=0)),
                ("new_reviews_this_month", models.IntegerField(default=0)),
                ("response_rate_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, default=0, null=True)),
                ("industry_avg_response_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, default=45, null=True)),
                ("requests_sent", models.IntegerField(default=0)),
                ("conversion_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=5, default=0, null=True)),
                ("last_fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_overview_snapshot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviews overview snapshot",
                "verbose_name_plural": "Reviews overview snapshots",
            },
        ),
    ]
